name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      interview_count:
        description: 'Number of interviews to generate'
        required: false
        default: '10'
      size_multiplier:
        description: 'Size multiplier for content'
        required: false
        default: '1.0'

jobs:
  test-x64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run full test suite
      run: |
        npm run test:full -- \
          ${{ github.event.inputs.interview_count || '10' }} \
          ${{ github.event.inputs.size_multiplier || '1.0' }}
      env:
        GITHUB_PAGES_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-x64-node${{ matrix.node }}
        path: test-results/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-x64-node${{ matrix.node }}
        path: dist/

  test-arm64:
    runs-on: ubuntu-24.04-arm
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run full test suite
      run: |
        npm run test:full -- \
          ${{ github.event.inputs.interview_count || '10' }} \
          ${{ github.event.inputs.size_multiplier || '1.0' }}
      env:
        GITHUB_PAGES_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-arm64
        path: test-results/

  deploy:
    needs: [test-x64]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-x64-node18
        path: dist/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: ${{ secrets.CNAME }}